# NAME:Dinkar Khattar
# EMAIL:dinkarkhattar@gmail.com
# ID:204818138


default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py

clean:
	rm -rf *.tar.gz lab3b

dist:
	tar -czf lab3b-204818138.tar.gz lab3b.py README Makefile
