# NAME:Taasin Saquib
# EMAIL: taasin.saquib@gmail.com	
# ID: 304757196


default: 
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py

clean:
	rm -rf *.tar.gz lab3b

dist: 
	tar -czf lab3b-404735401.tar.gz lab3b.py README Makefile 
