# NAME:Taasin Saquib
# EMAIL: taasin.saquib@gmail.com	
# ID: 304757196


CC = gcc
CFLAGS  = -g -Wall -Wextra

default: 
	$(CC) $(CFLAGS) -o lab3a lab3a.c 

clean:
	rm -rf *.tar.gz lab3a

dist: 
	tar -czf lab3a-304757196.tar.gz lab3a.c README Makefile ext2_fs.h
