# NAME: Dinkar Khattar, Suyash Saxena
# EMAIL: dinkarkhattar@ucla.edu, suyashs@ucla.edu
# ID: 204818138, 404735401

CC = gcc
CFLAGS  = -g -Wall -Wextra

default:
	$(CC) $(CFLAGS) -o lab3a lab3a.c

clean:
	rm -rf *.tar.gz lab3a

dist:
	tar -czf lab3a-204818138.tar.gz lab3a.c *.h README Makefile
